# Etapa 1: Construção da aplicação
FROM node:22.1.0 AS build

# Define o diretório de trabalho no contêiner
WORKDIR /app

# Copia os arquivos de configuração para o contêiner
COPY package.json package-lock.json ./

# Instala as dependências de produção
RUN npm install

# Copia todo o código-fonte para o contêiner
COPY . .

# Gera a build de produção da aplicação
RUN npm run build

# Etapa 2: Servir os arquivos estáticos com Nginx
FROM nginx:alpine

# Copia os arquivos estáticos gerados para o Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copia a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80 para o host
EXPOSE 80

# Manter o Nginx em execução no contêiner
CMD ["nginx", "-g", "daemon off;"]